
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hyllmee
 */
public class DutyManagement extends javax.swing.JFrame {
    private final DefaultListModel<String> listModel;
    private final ArrayList<String> taskList;
    
    
    private void updateList() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form DutyManagement
     */
    public DutyManagement() {
        initComponents();
        
            // Inisialisasi ArrayList untuk daftar tugas
        taskList = new ArrayList<>();

            // Inisialisasi List Model
        listModel = new DefaultListModel<>();
        DutyList.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        Add = new javax.swing.JPanel();
        NewDuty = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Deadline = new javax.swing.JLabel();
        Detail = new javax.swing.JLabel();
        txtNamaMatkul = new javax.swing.JTextField();
        txtDeadline = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        List = new javax.swing.JPanel();
        titledtls = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DutyList = new javax.swing.JList<>();
        DutyDetail = new javax.swing.JLabel();
        btnClean = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDutyDetail = new javax.swing.JTextArea();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        NewDuty.setFont(new java.awt.Font("Impact", 2, 18)); // NOI18N
        NewDuty.setText("Add New Duty");

        Nama.setText("Nama Mata Kuliah");

        Deadline.setText("Deadline Tugas");

        Detail.setText("Detail Tugas");

        txtNamaMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMatkulActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        jScrollPane3.setViewportView(txtDetail);

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(NewDuty)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(49, 49, 49)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(AddLayout.createSequentialGroup()
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nama)
                                    .addComponent(Deadline, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Detail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaMatkul)
                                    .addComponent(txtDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))))
                .addGap(30, 30, 30))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(NewDuty)
                .addGap(17, 17, 17)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(txtNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deadline)
                    .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Detail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSave))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Add Duty", Add);

        titledtls.setFont(new java.awt.Font("Harlow Solid Italic", 2, 18)); // NOI18N
        titledtls.setText("Duty List");

        DutyList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DutyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DutyListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DutyList);

        DutyDetail.setText("DutyDetail :");

        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        txtDutyDetail.setColumns(20);
        txtDutyDetail.setRows(5);
        jScrollPane2.setViewportView(txtDutyDetail);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListLayout = new javax.swing.GroupLayout(List);
        List.setLayout(ListLayout);
        ListLayout.setHorizontalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListLayout.createSequentialGroup()
                .addGroup(ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(titledtls))
                    .addGroup(ListLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DutyDetail)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addGap(11, 11, 11))
        );
        ListLayout.setVerticalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titledtls)
                .addGap(18, 18, 18)
                .addGroup(ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ListLayout.createSequentialGroup()
                        .addComponent(DutyDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(31, 31, 31)
                .addGroup(ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClean)
                    .addComponent(Exit))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Duty list", List);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String getDeadlineForTask(int selectedIndex) {
    // Implementasikan cara Anda untuk mendapatkan deadline berdasarkan indeks.
    if (selectedIndex >= 0 && selectedIndex < taskList.size()) {
        String selectedTask = taskList.get(selectedIndex);
        Map<String, String> taskDeadlines = new HashMap<>(); // Gantilah dengan struktur data yang sesuai.
        String deadline = taskDeadlines.get(selectedTask);

        if (deadline != null) {
            return deadline; // Kembalikan deadline jika ditemukan.
        }
    }
    
    return ""; // Jika tidak ada tugas yang dipilih atau deadline tidak ditemukan.
}
    private void DutyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DutyListMouseClicked
     if (evt.getClickCount() == 1) {
        int selectedIndex = DutyList.locationToIndex(evt.getPoint());
        if (selectedIndex >= 0 && selectedIndex < taskList.size()) {
            String selectedTask = taskList.get(selectedIndex);
            
            // Mengambil inputan dari txtDeadline dan txtDetail
            String selectedDeadline = txtDeadline.getText();
            String selectedDetail = txtDetail.getText();
            
            // Menampilkan detail tugas, deadline, dan detail pada txtDutyDetail
            txtDutyDetail.setText("Detail Tugas: " + selectedTask + "\nDeadline: " + selectedDeadline + "\nDetail: " + selectedDetail);
        }
    }
    }//GEN-LAST:event_DutyListMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        String newTask = txtNamaMatkul.getText();
        taskList.add(newTask);
        listModel.addElement(newTask); // Menambahkan tugas baru ke List Model
        txtNamaMatkul.setText(""); // Membersihkan input teks
        txtDeadline.setText(""); // Membersihkan input deadline
        txtDetail.setText(""); // Membersihkan input detail
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String newTask = txtNamaMatkul.getText();
        String deadline = txtDeadline.getText(); // Dapatkan teks dari input txtDeadline
        String detail = txtDetail.getText(); // Dapatkan teks dari input txtDetail

        taskList.add(newTask);
        listModel.addElement(newTask); // Menambahkan tugas baru ke List Model
        txtNamaMatkul.setText(""); // Membersihkan input teks
        // Membersihkan teks di txtDeadline dan txtDetail
        txtDeadline.setText("");
        txtDetail.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        int selectedIndex = DutyList.getSelectedIndex(); // Dapatkan indeks item yang dipilih

        if (selectedIndex >= 0) {
            // Hapus item yang sesuai dari taskList dan listModel
            taskList.remove(selectedIndex);
            listModel.removeElementAt(selectedIndex);

            // Membersihkan teks di dutydetail, txtDeadline, dan txtDetail
            txtDutyDetail.setText("");
            txtDeadline.setText("");
            txtDetail.setText("");
        }
    }//GEN-LAST:event_btnCleanActionPerformed

    private void txtNamaMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMatkulActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DutyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DutyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DutyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DutyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DutyManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JLabel Deadline;
    private javax.swing.JLabel Detail;
    private javax.swing.JLabel DutyDetail;
    private javax.swing.JList<String> DutyList;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel List;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NewDuty;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel titledtls;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextArea txtDutyDetail;
    private javax.swing.JTextField txtNamaMatkul;
    // End of variables declaration//GEN-END:variables

    
}
